POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "Jason Espallardo",
  "number": "123456789"
}

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "Jake Estipan"
}

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "number": "676767676767"
}

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "Ada Lovelace",
  "number": "6969696969"
}